### ISSUE TITLE
Could not find com.first.avatargenerator:AvatarImageGenerator:1.5.0

### ISSUE THREAD

**Issue by rafflypohan** [AmosKorir/AvatarImageGenerator#19]

**Comment by AmosKorir** [comment]
Add maven { url "https://jitpack.io" } to setting.gradle


`
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        jcenter() // Warning: this repository is going to shut down soon
    }
}
rootProject.name = "AvatarSample"
include ':app'
`

2. Add maven { url "https://jitpack.io" } to project root gradle file like below


`buildscript {
    repositories {

        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.0.3"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}`


3. add the dependency , Note the change below, because of jitpack

`implementation 'com.github.amoskorir:avatarimagegenerator:1.5.0'`
